feat: support unary operator not when building filters and improve boolean filter functions.
SAP/cloud-sdk-js pull request #1200
Opened 2021-04-14 09:07 UTC by jjtang1985

- [ ] Support unary operator `not` in the `filter()` of OData request builders.
- [ ] Filter functions with boolean return types can be used directly in the `filter()` of OData request builders without `equals(true)`.

2021-04-14 10:48 UTC, marikaner commented on CHANGELOG.md
> +- [odata] Filter functions with boolean return types can be used directly in the `filter()` of OData request builders without `equals(true)`.
Try to formulate it so that it matches the imperative case (check the examples on top of this file)

2021-04-14 11:10 UTC, marikaner requested changes
I think this is a good solution to the problem 😊
However, if I am not mistaken we should also be able to negate fields (see my comments) and I think this is currently not supported.

2021-04-14 11:10 UTC, marikaner commented on packages/core/src/odata-common/uri-conversion/get-filter.ts
> +    if (isBooleanFilterFunction(filter)) {
This function is getting bigger and bigger. I think I started that and I know this goes a little beyond this PR. Still, maybe it is time to split it into smaller functions?

For example: 
```ts
...
if (isFilterLink(filter)) {
  return getODataExpressionForFilterLink(...);
}
if (isFilter(filter)) {
  return getODataExpressionForFilter(...);
}
...
```

2021-04-14 15:38 UTC, jjtang1985 commented on packages/core/src/odata-common/filter/unary-filter.ts
> +    public singleOperand: Filterable<EntityT>,
Don't get it. Maybe a call?

2021-04-14 15:43 UTC, jjtang1985 commented on packages/core/src/odata-common/uri-conversion/get-filter.ts
> +      return `${filter.operator} (${getODataFilterExpression(
Here is a typical example:
```
not endswith(Name,'ilk')
```
where you see space in between.
We add a pair of `()` for the inner filter as a rule for all kinds of filters, meaning there is no difference logically.
I don't have strong opinion on this.

2021-04-16 07:30 UTC, FrankEssenberger approved these changes
LGTM @jjtang1985 can you adjust the documentation to include an example of boolean filter without the equals true (explaining the two ways and what they are serialized too and that they are in principle both allowed but some backends accept only one of the two) and the `not` filter of course.

2021-04-16 07:34 UTC, jjtang1985 commented
> LGTM @jjtang1985 can you adjust the documentation to include an example of boolean filter without the equals true (explaining the two ways and what they are serialized too and that they are in principle both allowed but some backends accept only one of the two) and the not filter of course.

I'll update the docs with new examples.

2021-04-16 07:34 UTC, merged