fix: encode full filter parameter once
SAP/cloud-sdk-js pull request #1283
Opened 2021-05-10 15:59 UTC by FrankEssenberger

Moved the encode method up to the last point when the filter string is returned.

2021-05-18 07:02 UTC, jjtang1985 requested changes
Looks good for the filter, but we also want to encode the path and other query parameters.

2021-05-18 12:58 UTC, FrankEssenberger commented on CHANGELOG.md
> +- [odata] Fix encoding of filter strings.
I thought about this but it seemed not to be necessary. So the [url](https://github.com/SAP/cloud-sdk-js/blob/74815776f7efa95fae93566fca166de2cacc64cb/packages/core/src/odata-common/request/odata-request.ts#L60) contains only the [query](https://github.com/SAP/cloud-sdk-js/blob/74815776f7efa95fae93566fca166de2cacc64cb/packages/core/src/odata-common/request/odata-request.ts#L145) part which needs to be encoded. I went than to the get all [implementation](https://github.com/SAP/cloud-sdk-js/blob/74815776f7efa95fae93566fca166de2cacc64cb/packages/core/src/odata-common/request/odata-get-all-request-config.ts#L41-L59) which contained the:
- select
- expand
- orderBy
- filter
as parts. I think only the filter could contain parts which need encoding. Our naming convention in the generator and restrictions in TS should make encoding for the other parts not necessary.

2021-05-19 07:13 UTC, jjtang1985 commented on CHANGELOG.md
> +- [odata] Fix encoding of filter strings.
### query parameters
- question: how about properties containing umlaut characters, which might be used by `select`/`expand`/`orderBy`?
- we also have custom query parameters, which might be `?objectName=' space space '`.
### path
- service path/custom service path might need encoding

2021-05-19 09:37 UTC, FrankEssenberger commented on CHANGELOG.md
> +- [odata] Fix encoding of filter strings.
For the custom path and parameter I would say we should keep them as they are. Regarding the special characters in select, expand this is true in principal.

2021-05-20 12:44 UTC, jjtang1985 approved these changes
As discussed, we cannot encode the whole URL, as the custom part should not be encoded. Splitting the encoding job is also error prone, so we leave it for now and wait until further feedbacks.

2021-05-20 13:12 UTC, merged

2021-05-25 06:32 UTC, jjtang1985 commented
related to https://github.com/SAP/cloud-sdk-js/issues/1226