chore: New line in perService config
SAP/cloud-sdk-js pull request #1305
Opened 2021-05-20 13:22 UTC by FrankEssenberger

Add a new line at the end of the per-service-config.json so that the prettier we provide does not change the file.

2021-05-26 11:15 UTC, marikaner requested changes
Forgot to send this out before...

2021-06-07 15:25 UTC, FrankEssenberger commented on packages/openapi-generator/src/generator.spec.ts
> +    it('adds a new line at the options', async () => {
you are right, that it is implicitly tested, but I prefer to have a separate test but I adjust it.

2021-06-07 15:42 UTC, FrankEssenberger commented on packages/util/src/string-formatter.ts
> +export function jsonStringify(json: any): string {
renamed the function

2021-06-10 15:15 UTC, marikaner approved these changes
👍
I still have to ask for one thing: `jsonFileFormat` does not really follow our style guide (https://github.com/SAP/cloud-sdk-js/blob/main/STYLEGUIDE.md#use-verbs-in-function-names).
Maybe consider: `formatJson` ?

2021-06-18 19:13 UTC, merged