chore: fix circular dependencies
SAP/cloud-sdk-js pull request #1861
Opened 2021-12-01 14:49 UTC by FrankEssenberger

Please provide a description of what your change does and why it is needed.

Closes SAP/cloud-sdk-backlog#ISSUENUMBER.

2021-12-02 11:16 UTC, marikaner requested changes
I think the util package is still needed for test-util (but I wonder why the dependency check does not fail, so maybe I am seeing it wrong?).
Other than that I mostly have questions.

2021-12-02 11:16 UTC, marikaner commented on packages/connectivity/src/scp-cf/destination/destination-from-service.ts
> +        decoded: await verifyJwt(options.jwt, creds.uaadomain, options),
This does not seem related to this PR, did you add this change on purpose?

2021-12-02 11:16 UTC, marikaner commented on CHANGELOG-v2.md
> +- [connectivity] `verifyJwt` needs the uaaDomain as input. The domain can be obtained from the XSUAA credentials.
Is this related to this PR? Was this added on purpose?

2021-12-02 11:16 UTC, marikaner commented on packages/connectivity/src/scp-cf/destination/proxy-util.spec.ts
> +import { unmockAllTestDestinations } from '../../../../test-util/src';
I fail to recognize where the counterpart is called (`mockAllTestDestinations`). A quick search on my local state reveals that this is only called in the integration tests and in the tests of `test-util`. I wonder why we even need to call this...

2021-12-03 14:38 UTC, FrankEssenberger commented
Discussion marika
 - See if mock all is used at all
 - Use old JWT api and see why madge is complaining wiht modern ES imports.

2021-12-06 11:33 UTC, marikaner approved these changes
LGTM

2021-12-06 11:38 UTC, merged