chore: Use xssec also for validation
SAP/cloud-sdk-js pull request #2041
Opened 2022-01-28 11:54 UTC by FrankEssenberger

Closes SAP/cloud-sdk-backlog#479.

Replace the custom verification key implementation with the build in one by xssec.

2022-02-17 10:36 UTC, florian-richter reviewed
@FrankEssenberger could you give some more context. Since there are no release notes attached, is this a change that does not change user interaction? Anything reviewers should check specifically?

2022-02-17 10:36 UTC, florian-richter commented on packages/connectivity/src/scp-cf/jwt.spec.ts
> +    }, 600000);
Is this intended to stay? Running it 999 times may slow down tests a bit much, is it not?

2022-02-21 13:50 UTC, FrankEssenberger commented
> @FrankEssenberger could you give some more context. Since there are no release notes attached, is this a change that does not change user interaction? Anything reviewers should check specifically?

I added also @jjtang1985 since he wrote most of the caching. What should be ensure is the behavior, that per default the keys are cached. Also that it fails if it can not be verified should be behave the same. The error messages will differ since the `xssev` throws the errors now.

2022-02-22 08:53 UTC, jjtang1985 requested changes
Looks good to me in general.
I left some comments.

2022-02-22 08:53 UTC, jjtang1985 commented on CHANGELOG.md
> +- [connectivity] Use the cache of `xssec` library to cache verification certificates.
I guess you need to merge the main branch, as other changelog items were released.

2022-02-22 08:53 UTC, jjtang1985 commented on packages/connectivity/src/scp-cf/jwt.spec.ts
> +            'Obtained token keys from UAA, but key with requested keyID "https://my-jku-url.authentication.sap.hana.ondemand.comkey-id-1" still not found in cache.'
I know this comes from xssec, but if I disable the cacheVerificationKeys, and the error message still says the key is not found in cache, I would be confused.

2022-02-22 08:54 UTC, jjtang1985 commented
> I added also @jjtang1985 since he wrote most of the caching. What should be ensure is the behavior, that per default the keys are cached. Also that it fails if it can not be verified should be behave the same. The error messages will differ since the xssev throws the errors now.

Actually for verification key, @marikaner wrote most of the code. Please have a look, as this is a sensitive topic.

2022-02-28 08:43 UTC, jjtang1985 approved these changes

2022-02-28 08:44 UTC, merged