reafactor: make sending email parallel
SAP/cloud-sdk-js pull request #2788
Opened 2022-08-23 04:45 UTC by shojisoma

Closes [SAP/cloud-sdk-backlog#ISSUENUMBER.](https://github.com/SAP/cloud-sdk-backlog/issues/820)

this converts the sequential email sending process into a parallel one.

2022-08-23 08:14 UTC, FrankEssenberger approved these changes
LGTM - did you check that the E2E tests are green?

2022-08-23 09:02 UTC, FrankEssenberger commented on packages/mail-client/src/mail-client.ts
> +    responces => {
[req] typo

2022-08-25 00:27 UTC, shojisoma commented on packages/mail-client/src/mail-client.ts
> +    responces => {
done

2022-08-29 11:56 UTC, jjtang1985 requested changes
As the OnPrem (cloud worked) e2e tests failed, I would not merge this.
Potential follow up would be adding an option so users can decide the strategy (parallel or in sequential).

2022-08-29 14:29 UTC, FrankEssenberger commented
> As the OnPrem (cloud worked) e2e tests failed, I would not merge this. Potential follow up would be adding an option so users can decide the strategy (parallel or in sequential).

Was the fail surely related to the code change so do they work with the `main` codeline?

2022-08-30 09:07 UTC, jjtang1985 commented
> Was the fail surely related to the code change so do they work with the main codeline?

The app was re-deployed after updating the SDK Core manually by copy/pasting the mail-client dist folder from the PR branch.

2022-08-31 11:18 UTC, jjtang1985 commented
I'll create a new PR

2022-08-31 11:18 UTC, closed without merging