try version range using caret
SAP/cloud-sdk-js pull request #4927
Opened 2024-08-19 10:05 UTC by deekshas8

Closes SAP/cloud-sdk-backlog#ISSUENUMBER.

2024-08-19 10:25 UTC, tomfrenken approved these changes
LGTM

2024-08-19 13:14 UTC, tomfrenken requested changes
Since we apparently need to make some type changes, I'll block it for now

2024-08-20 09:25 UTC, deekshas8 commented on package.json
> +    "typedoc": "^0.26.0",
[info] typedoc 0.26 added support for TS 5.4.

2024-08-20 09:27 UTC, deekshas8 commented on build-packages/check-pr/tsconfig.json
> +    "module": "Node16",
[info] Added these options explicitly here to resolve the error in `validator.ts`:
 `Named capturing groups are only available when targeting 'ES2018' or later`

2024-08-20 09:29 UTC, deekshas8 commented on packages/odata-common/src/request-builder/batch/batch-response-deserializer.ts
> +      isSuccess: (): this is
I assume TS 5.5.4 enforces stricter checks on predicates compared to 5.4. The error here was: 

```
Type '() => true' is not assignable to type '() => this is ReadResponse<DeSerializersT> | WriteResponses<DeSerializersT>'.
  Signature '(): true' must be a type predicate.ts(2322)
batch-response.ts(15, 3): The expected type comes from property 'isSuccess' which is declared here on type 'ReadResponse<DeSerializersT>'
```

2024-08-20 10:45 UTC, tomfrenken approved these changes
LGTM, I took a look at the changelog from typescript, and the types seem to get narrowed stronger with the latest version, this also explains all the deletions in the generated clients.

2024-08-20 14:13 UTC, merged