chore: Moment poc ADR
SAP/cloud-sdk-js pull request #934
Opened 2021-01-25 10:26 UTC by jjtang1985

In the ADR `0015-date-time-handling.md`, we decided to make an interface so users could choose the date time lib and custom the (de)serialiser. 
The [PoC](https://github.com/SAP/cloud-sdk-js/pull/921) of such design was successful.
This PR reflects the status of the PoC in the aspects:
- new api design
- assumption
- scope
- next steps

2021-01-27 09:48 UTC, FrankEssenberger commented on knowledge-base/adr/0015-date-time-handling.md
> +- OData V2 has the same complexity as the OData V4.
Perhaps add also the point that the URL uses just the serializers and no extra work is needed.

2021-01-27 09:49 UTC, FrankEssenberger commented on knowledge-base/adr/0015-date-time-handling.md
> +For example, for `ODataV4`, 4 edm types (`Edm.DateTimeOffset`, `Edm.Date`, `Edm.Duration` and `Edm.TimeOfDay`) are relevant, which means it will introduce 4 generic types for all the classes mentione
Perhaps you can add the generic types later for your number,string example with a reference here. Then it becomes more clear what is meant by this new objects.

2021-01-27 09:51 UTC, FrankEssenberger commented on knowledge-base/adr/0015-date-time-handling.md
> +```
See comment above of giving the generic entiy TestEntityTemporal<A,B> and how it relates to the number of properties and types.

2021-01-27 09:53 UTC, FrankEssenberger commented on knowledge-base/adr/0015-date-time-handling.md
> +### Scope
One important part of the scope is missing IMO: We want to save space so if you use a non moment middle ware the moment dependency should not appear at all in your dependencies. Add a paragraph how this is achieved.

2021-01-27 09:53 UTC, FrankEssenberger requested changes
Consider my comments.

2021-01-28 09:57 UTC, jjtang1985 commented on knowledge-base/adr/0015-date-time-handling.md
> +- Serializer has the same complexity as the Deserializer.
```suggestion
- Serializer has the same complexity as the Deserializer.
- The URL converter uses the serialiser, so it might not be part of the middleware.
```

2021-01-28 10:02 UTC, jjtang1985 commented on knowledge-base/adr/0015-date-time-handling.md
> +- OData V2 has the same complexity as the OData V4.
```suggestion
- OData V2 has the same complexity as the OData V4.
- Advanced data type like Complex/Collection type can be handled like the basic edm type.
```

2021-01-28 10:05 UTC, jjtang1985 commented on knowledge-base/adr/0015-date-time-handling.md
> +For example, for `ODataV4`, 4 edm types (`Edm.DateTimeOffset`, `Edm.Date`, `Edm.Duration` and `Edm.TimeOfDay`) are relevant, which means it will introduce 4 generic types for all the classes mentione
```suggestion
For example, for `ODataV4`, 4 edm types (`Edm.DateTimeOffset`, `Edm.Date`, `Edm.Duration` and `Edm.TimeOfDay`) are relevant, which means it will introduce 4 generic types for all the classes mentioned above.
In the PoC example, the string/number example looks like below, where only two generic types are used:
```
export class TestEntity<T1 = string, T2 = number> extends EntityV4<T1, T2> implements TestEntityType<T1, T2> {}

```

2021-01-28 16:40 UTC, FrankEssenberger commented on knowledge-base/adr/0015-date-time-handling.md
> +export class TestEntityTemporal<T1 = string, T2 = number> extends EntityV4<T1, T2> implements TestEntityType<T1, T2> {}
Could you add two dummy properties with the type T1 and T2 so that it becomes imediatelly clear.

2021-01-28 16:40 UTC, FrankEssenberger approved these changes
LGTM

2021-01-29 08:48 UTC, jjtang1985 commented on knowledge-base/adr/0015-date-time-handling.md
> +export class TestEntityTemporal<T1 = string, T2 = number> extends EntityV4<T1, T2> implements TestEntityType<T1, T2> {}
```suggestion
export class TestEntityTemporal<T1 = string, T2 = number> extends EntityV4<T1, T2> implements TestEntityType<T1, T2> {
  stringProperty?: T1;
  int32Property?: T2;
  ...
}
```

2021-01-29 08:57 UTC, merged