chore: move cli to main repo
SAP/cloud-sdk-js pull request #943
Opened 2021-01-27 17:36 UTC by FrankEssenberger

Move the https://github.com/SAP/cloud-sdk-cli to the main repo.

Remaining tasks or follow up tasks:
- Use mock FS system for tests inside the repo
- Properly integrate the commands in each other in other words reuse the command from the generator and openapi-generator in the cli.
- Enable the nightly tests
- Put note on cli page to use this repo

2021-02-01 10:05 UTC, jjtang1985 requested changes

2021-02-01 10:06 UTC, jjtang1985 requested changes
I'm happy to see the execution time of the pipeline is not affected.

2021-02-01 10:10 UTC, jjtang1985 commented
I failed to make the review in one action..

2021-02-01 13:46 UTC, FrankEssenberger commented on packages/cli/package.json
> +    "access": "private"
I have create some follow up tickets I would like to do before releasing.

2021-02-02 13:26 UTC, jjtang1985 approved these changes
LGTM

2021-02-03 08:13 UTC, merged